name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ master ]  # Trigger on push to 'master' branch

# Add permissions for GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable  # Use stable Flutter version

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build Flutter web app
      - name: Build web
        run: flutter build web --release

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web  # Deploy the 'build/web' folder
          keep_files: false        # Clean old files before deployment