name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches: [ master ]  # Trigger on push to 'master' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable  # Use stable Flutter version

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build Flutter web app (no base-href needed for Firebase)
      - name: Build web
        run: flutter build web --release

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: altira-ec724  # Replace with your actual project ID
          channelId: live